// // Variable
// var x = 0;
// x = 1;

// // Costant
// const y = 0;
// y = 1;

var canvas;
var ctx;
var unit = 9;

window.onload = init;

function init() {
    canvas = document.getElementById("myCanvas");
    ctx = canvas.getContext("2d");
    // drawRuler(5);
    ctx.fillStyle = "black";
    ctx.fillRect(35 * unit, 0 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(40 * unit, 0 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(45 * unit, 0 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(25 * unit, 5 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(30 * unit, 5 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(35 * unit, 5 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(40 * unit, 5 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(45 * unit, 5 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(50 * unit, 5 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(55 * unit, 5 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(20 * unit, 10 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(25 * unit, 10 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(30 * unit, 10 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(35 * unit, 10 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(40 * unit, 10 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(45 * unit, 10 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(50 * unit, 10 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(55 * unit, 10 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(60 * unit, 10 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(15 * unit, 15 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(20 * unit, 15 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(25 * unit, 15 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(30 * unit, 15 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(35 * unit, 15 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(40 * unit, 15 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(45 * unit, 15 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(50 * unit, 15 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(55 * unit, 15 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(60 * unit, 15 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(65 * unit, 15 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(15 * unit, 20 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(20 * unit, 20 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(25 * unit, 20 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(30 * unit, 20 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(35 * unit, 20 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(40 * unit, 20 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(45 * unit, 20 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(50 * unit, 20 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(55 * unit, 20 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(60 * unit, 20 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(65 * unit, 20 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(10 * unit, 25 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(15 * unit, 25 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(20 * unit, 25 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(25 * unit, 25 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(30 * unit, 25 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(35 * unit, 25 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(40 * unit, 25 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(45 * unit, 25 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(50 * unit, 25 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(55 * unit, 25 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(60 * unit, 25 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(65 * unit, 25 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(70 * unit, 25 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(10 * unit, 30 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(15 * unit, 30 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(20 * unit, 30 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(25 * unit, 30 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(55 * unit, 30 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(60 * unit, 30 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(65 * unit, 30 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(70 * unit, 30 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(10 * unit, 35 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(15 * unit, 35 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(20 * unit, 35 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(5 * unit, 35 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(10 * unit, 35 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(60 * unit, 35 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(65 * unit, 35 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(70 * unit, 35 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(75 * unit, 35 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(5 * unit, 40 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(10 * unit, 40 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(15 * unit, 40 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(65 * unit, 40 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(70 * unit, 40 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(75 * unit, 40 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(5 * unit, 45 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(10 * unit, 45 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(15 * unit, 45 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(25 * unit, 45 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(55 * unit, 45 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(65 * unit, 45 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(70 * unit, 45 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(75 * unit, 45 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(10 * unit, 50 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(15 * unit, 50 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(25 * unit, 50 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(30 * unit, 50 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(50 * unit, 50 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(55 * unit, 50 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(65 * unit, 50 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(70 * unit, 50 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(15 * unit, 55 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(20 * unit, 55 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(60 * unit, 55 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(65 * unit, 55 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(25 * unit, 60 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(30 * unit, 60 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(35 * unit, 60 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(40 * unit, 60 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(45 * unit, 60 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(50 * unit, 60 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(55 * unit, 60 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(25 * unit, 65 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(30 * unit, 65 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(35 * unit, 65 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(40 * unit, 65 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(45 * unit, 65 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(50 * unit, 65 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(55 * unit, 65 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(20 * unit, 70 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(25 * unit, 70 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(30 * unit, 70 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(35 * unit, 70 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(40 * unit, 70 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(45 * unit, 70 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(50 * unit, 70 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(55 * unit, 70 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(60 * unit, 70 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(15 * unit, 75 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(20 * unit, 75 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(25 * unit, 75 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(30 * unit, 75 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(35 * unit, 75 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(40 * unit, 75 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(45 * unit, 75 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(50 * unit, 75 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(55 * unit, 75 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(60 * unit, 75 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(65 * unit, 75 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(20 * unit, 80 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(25 * unit, 80 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(30 * unit, 80 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(35 * unit, 80 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(40 * unit, 80 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(45 * unit, 80 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(50 * unit, 80 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(55 * unit, 80 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(60 * unit, 80 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(25 * unit, 85 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(30 * unit, 85 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(35 * unit, 85 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(40 * unit, 85 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(45 * unit, 85 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(50 * unit, 85 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(55 * unit, 85 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(20 * unit, 90 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(25 * unit, 90 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(30 * unit, 90 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(35 * unit, 90 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(40 * unit, 90 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(45 * unit, 90 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(50 * unit, 90 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(55 * unit, 90 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(60 * unit, 90 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(15 * unit, 95 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(20 * unit, 95 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(25 * unit, 95 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(30 * unit, 95 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(35 * unit, 95 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(40 * unit, 95 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(45 * unit, 95 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(50 * unit, 95 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(55 * unit, 95 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(60 * unit, 95 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(65 * unit, 95 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(35 * unit, 100 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(45 * unit, 100 * unit, 5 * unit, 5 * unit);
    ctx.fillStyle = "grey";
    ctx.fillRect(30 * unit, 30 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(35 * unit, 30 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(40 * unit, 30 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(45 * unit, 30 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(50 * unit, 30 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(25 * unit, 35 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(55 * unit, 35 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(20 * unit, 40 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(60 * unit, 40 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(20 * unit, 50 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(25 * unit, 55 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(60 * unit, 50 * unit, 5 * unit, 5 * unit);
    ctx.fillRect(55 * unit, 55 * unit, 5 * unit, 5 * unit);
}